pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: git
    image: linuxserver/yq
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
      - name: jenkins-kanikoa
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: jenkins-kanikoa
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
"""
    }
  }

  stages {
    stage ('checkout'){
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'jenkins-ci']]]], userRemoteConfigs: [[url: 'https://github.com/ngdtrunguit/forCRP2.0.git']]])
      }
    }
    stage('Kaniko Build & Push Image') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {

          script {
            sh 'ls'
            sh 'pwd'
            dir('jenkins-ci') {
              sh 'pwd'
              sh 'ls'
              sh '''#!/busybox/sh
              echo "FROM jenkins/inbound-agent:latest" > Dockerfile
              /kaniko/executor --context `pwd` \
                             --destination trungnguyenprojectcrp2.azurecr.io/test-ci:1.0.${BUILD_NUMBER}
              '''
            }
          }
        }
      }
    }
    stage('Update tag in YAML') {
      environment {
        TAG = "1.0.${BUILD_NUMBER}"
      }
      steps {
        container(name: 'git') {
          withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              sh 'apk update && apk add git && apk add yq'
              sh 'git init'
              sh 'git config --global --add safe.directory /home/jenkins/agent/workspace/demo'
              sh 'git clone https://github.com/ngdtrunguit/forCRP2.0.git'
              sh 'pwd'
              sh 'ls'
              sh 'ls forCRP2.0/'
              sh 'cd forCRP2.0/test-ci'
              sh 'ls'
              sh 'git pull origin main'
              sh 'git config user.email ngdtrunguit@gmail.com'
              sh 'git config user.name ngdtrunguit'
              sh 'cat values.yaml'
              sh 'yq eval '.image.tag = env(TAG)' -i values.yaml'
              sh 'cat values.yaml'
              sh 'git add .'
              sh 'git commit -m "Update app image tag to $TAG"'
              sh 'git push https://${GIT_PASSWORD}@github.com/${GIT_USERNAME}/forCRP2.0.git HEAD:main'
              }

        }
      }
    }
  }

    // stage('Deploy App to Kubernetes') {     
    //   steps {
    //     container('kubectl') {
    //       withCredentials([file(credentialsId: 'mykubeconfig', variable: 'KUBECONFIG')]) {
    //         sh 'sed -i "s/<TAG>/${BUILD_NUMBER}/" myweb.yaml'
    //         sh 'kubectl apply -f myweb.yaml'
    //       }
    //     }
    //   }
    // }
  }