pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  annotations: 
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: git
    image: linuxserver/yqk
    command:
    - sleep
    args:
    - 9999999
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
"""
    }
  }

  stages {
    stage ('checkout'){
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'jenkins-ci']]]], userRemoteConfigs: [[url: 'https://github.com/ngdtrunguit/forCRP2.0.git']]])
      }
    }
    stage('Kaniko Build & Push Image') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {

          script {
            dir('jenkins-ci') {
              sh 'pwd'
              sh 'ls'
              sh '''#!/busybox/sh
              /kaniko/executor --dockerfile `pwd`/Dockerfile \
                            --context `pwd` \
                             --destination trungnguyenprojectcrp2.azurecr.io/test-ci:1.0.${BUILD_NUMBER}
              '''
            }
          }
        }
      }
    }
    stage('Update tag in YAML') {
      environment {
        TAG = "1.0.${BUILD_NUMBER}"
      }
      steps {
        container(name: 'git') {
          withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              sh """
              apk update && apk add git && apk add yq
              git init
              git config --global --add safe.directory /home/jenkins/agent/workspace/demo
              git clone https://github.com/ngdtrunguit/forCRP2.0.git
              cd forCRP2.0/test-ci
              git config user.email ngdtrunguit@gmail.com
              git config user.name ngdtrunguit
              cat values.yaml
              yq eval '.image.tag = env(TAG)' -i values.yaml
              cat values.yaml
              echo $TAG
              git add . 
              git commit -m "Update app image tag to $TAG"
              git pull origin main
              git push https://${GIT_PASSWORD}@github.com/${GIT_USERNAME}/forCRP2.0.git HEAD:main
              """
        }
      }
    }
  }
  }
}