apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: release-name-test-ci
  labels:
    app: test-ci
    chart: test-ci-0.1.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-ci
      release: release-name
  strategy:
    blueGreen:
      activeService: release-name-test-ci
      previewService: release-name-test-ci-preview
  template:
    metadata:
      labels:
        app: test-ci
        release: release-name
    spec:
      containers:
        - name: test-ci
          image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  strategy:
    blueGreen: 
      activeService: release-name-test-ci
      previewService: release-name-test-ci-preview
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60