name: Docker Image CI to ACR

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: test-ci
  IMAGE_TAG: 1.0.${{ github.run_number }} # GITHUB_RUN_NUMBER }}
  registry: ${{ secrets.ACR_ENDPOINT }}
  username: ${{ secrets.ACR_USERNAME }}
  password: ${{ secrets.ACR_PASSWORD }}


jobs:

  build:
    runs-on: ubuntu-latest
# Set directory for CI subfolder
    defaults:
      run:
        working-directory: test-ci
# Checkout 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
# Login to ACR
    # - name: Log into registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ${{ secrets.ACR_ENDPOINT }}
    #     username: ${{ secrets.ACR_USERNAME }}
    #     password: ${{ secrets.ACR_PASSWORD }}
#Build and Push Docker Image to ACR
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
#        docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
# Update Image Tag to values.yaml
    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'test-ci/values.yaml'
        branch: main
        targetBranch: main
        masterBranchName: main
        commitChange: true
        token: ${{ secrets.GH_TOKEN }}
        message: 'Update CI Images' 
        changes: |
          {
            "test-ci/values.yaml": {
              "image.tag": "${{ env.IMAGE_TAG }}"
            }
          }