name: Docker Image CI to ACR

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: test-ci
  registry: ${{ secrets.ACR_ENDPOINT }}
  username: ${{ secrets.ACR_USERNAME }}
  password: ${{ secrets.ACR_PASSWORD }}
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      working-directory: test-ci

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      working-directory: test-ci

    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      working-directory: test-ci

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          version=${{ steps.tag.outputs.tag }}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
      working-directory: test-ci
