name: 'terraform-remote-state'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
   
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
env: 
  #ROOT_PATH: '${{github.workspace}}/'
  ARM_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  

jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    
    steps:
    - name: print path
      run: echo 'path ::${{github.workspace}}/${{ inputs.ROOT_PATH }}'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.4
    - name: terraform init
      run: terraform init

    - name: terraform Plan
      run: terraform plan 
